#!/usr/bin/env bash
# runner-token.sh [--print] - issue a Gitea Actions runner registration token and write it into infra/.env.
#
#   infra/runner-token.sh              generate a token and store it, then recreate the runners
#   infra/runner-token.sh --print      print a token and touch nothing
#
# A registration token can only be issued by a running Gitea, which is the whole reason the stack has a
# two-step bootstrap: the first `docker compose -f infra/compose.yaml up -d` starts Gitea and a runner with an
# empty token, the runner restart-loops, this script fills the gap, and a second `up -d` recreates the runners
# with a token they can register with.
#
# The token is generated by the gitea CLI INSIDE the container. The CLI reaches the running server over its
# internal API using the config at /data/gitea/conf/app.ini, so it has to run where that server and that file
# are - running it on the host against a copy of the config would talk to nothing.
#
# The token is a bearer credential for enrolling a runner into this Gitea, so it is written into infra/.env,
# which is gitignored, and never echoed unless you ask for --print.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ENV_FILE=${ENV_FILE:-"${HERE}/.env"}
ENV_EXAMPLE=${ENV_EXAMPLE:-"${HERE}/.env.example"}
GITEA_CONTAINER=${GITEA_CONTAINER:-skill-suite-gitea}
GITEA_CONFIG=${GITEA_CONFIG:-/data/gitea/conf/app.ini}
TOKEN_KEY=GITEA_RUNNER_REGISTRATION_TOKEN

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m ok\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mFAIL\033[0m %s\n' "$*" >&2; exit 1; }

usage() {
    cat <<EOF
runner-token.sh - issue a Gitea Actions runner registration token.

usage: infra/runner-token.sh [--print]

  --print      write the token to stdout and leave ${ENV_FILE##*/} alone
  -h, --help   show this help

env overrides: GITEA_CONTAINER (default skill-suite-gitea), ENV_FILE, ENV_EXAMPLE, GITEA_CONFIG
EOF
}

# Ask the running Gitea for a fresh token. Only the last non-empty stdout line is taken: the CLI prints the
# token on its own, but a Gitea that logs to stdout would otherwise glue a log line onto it.
generate_token() {
    local output token

    command -v docker >/dev/null 2>&1 || die "docker is not installed"
    [[ $(docker inspect --format '{{.State.Running}}' "${GITEA_CONTAINER}" 2>/dev/null || true) == true ]] \
        || die "container ${GITEA_CONTAINER} is not running - start it with:
     docker compose -f infra/compose.yaml up -d"

    output=$(docker exec -u git "${GITEA_CONTAINER}" \
        gitea --config "${GITEA_CONFIG}" actions generate-runner-token 2>/dev/null) \
        || die "gitea could not issue a runner token; check 'docker logs ${GITEA_CONTAINER}'"

    token=$(printf '%s' "${output}" | tr -d '\r' | awk 'NF { line = $1 } END { print line }')

    [[ -n ${token} ]] || die "gitea returned an empty runner token"
    [[ ${token} != *[[:space:]]* ]] || die "gitea returned something that is not a single token: '${token}'"

    printf '%s' "${token}"
}

# Replace the token line in an env file, append it when absent, and create the file from the example when it
# does not exist yet. awk into a temp file and mv, rather than `sed -i`: BSD sed (macOS) requires an argument
# after -i and GNU sed refuses one, so there is no portable in-place sed. The move is also atomic, so an
# interrupted run cannot leave a half-written .env.
write_env_token() {
    local env_file=$1 example=$2 token=$3 tmp

    if [[ ! -f ${env_file} ]]; then
        [[ -f ${example} ]] || die "neither ${env_file} nor ${example} exists; nothing to write into"
        cp "${example}" "${env_file}"
        log "created ${env_file} from ${example##*/}"
    fi

    tmp=$(mktemp "${env_file}.XXXXXX") || die "could not create a temporary file beside ${env_file}"
    chmod 600 "${tmp}"

    awk -v key="${TOKEN_KEY}" -v value="${token}" '
        !replaced && $0 ~ "^[[:space:]]*" key "=" { print key "=" value; replaced = 1; next }
        { print }
        END { if (!replaced) print key "=" value }
    ' "${env_file}" >"${tmp}" || { rm -f "${tmp}"; die "could not rewrite ${env_file}"; }

    mv "${tmp}" "${env_file}" || { rm -f "${tmp}"; die "could not replace ${env_file}"; }
}

main() {
    local print_only=0 token

    while [[ $# -gt 0 ]]; do
        case $1 in
            --print)    print_only=1; shift ;;
            -h|--help)  usage; exit 0 ;;
            *)          usage >&2; die "unknown argument: $1" ;;
        esac
    done

    log "asking ${GITEA_CONTAINER} for a runner registration token"
    token=$(generate_token)

    if [[ ${print_only} -eq 1 ]]; then
        printf '%s\n' "${token}"
        return 0
    fi

    write_env_token "${ENV_FILE}" "${ENV_EXAMPLE}" "${token}"
    ok "${TOKEN_KEY} written to ${ENV_FILE}"

    printf '\n     Now recreate the runners so they pick it up:\n'
    printf '       docker compose -f infra/compose.yaml up -d\n\n'
}

# Only run when executed. Sourcing the script exposes write_env_token and generate_token on their own, which
# is what the tests do.
if [[ ${BASH_SOURCE[0]} == "${0}" ]]; then
    main "$@"
fi
