<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-Skill_Suite-2cd53e4f-0953-4b52-b644-e7aa5e3bce2e</UserSecretsId>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0"/>
        <PackageReference Include="Mediator.Abstractions" Version="3.1.0-rc.1"/>
        <PackageReference Include="MudBlazor" Version="9.0.0"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.10.0"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Skill.Suite.Application\Skill.Suite.Application.csproj"/>
        <ProjectReference Include="..\Skill.Suite.Infra\Skill.Suite.Infra.csproj"/>
        <ProjectReference Include="..\Skill.Suite.Domain\Skill.Suite.Domain.csproj"/>
    </ItemGroup>

</Project>
